### ISSUE TITLE
Emit the updated `element` in the `ReturnFormat.OBJECT` return format

### ISSUE THREAD

**Issue by bramus** [bramus/style-observer#10]
> Can you please emit the updated `element`

_Originally posted by @EswaramoorthyKarthikeyan in https://github.com/bramus/style-observer/issues/2#issuecomment-2416717295_

**Comment by EswaramoorthyKarthikeyan** [comment]
Thank you for considering.

**Comment by bramus** [comment]
This has been added in the `1.3.0` release.
