### ISSUE TITLE
Add extended return format

### ISSUE THREAD

**Issue by bramus** [bramus/style-observer#8]
See https://github.com/bramus/style-observer/issues/1#issuecomment-2323477477 _(and follow-up comments)_ for discussion.

The idea it to allow one to choose between returning only the value, or returning a more extended object that holds more info.

```js
[
  {"propertyName": "margin", "value": "40px", "previousValue": "20px", "changed": true},
  {"propertyName": "color", "value": "rgb(0, 0, 0)", "previousValue": "rgb(0, 0, 0)", "changed": false}
]
```

This would be opt-in, through an option named `ReturnFormat`: `VALUE_ONLY` _(default)_ or `OBJECT`

**Comment by faizanu94** [comment]
Hey @bramus - I've now implemented this feature in [this](https://github.com/bramus/style-observer/pull/9) PR - following our [decision](https://github.com/bramus/style-observer/pull/6#issuecomment-2327424152) to split this from the optimized change detection PR. I’ve focused on enhancing modularity and introduced a flag for backward compatibility
